### ISSUE TITLE
Update Node and NPM dependencies

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#11]
The application was written ~3 years ago with Node.js 12. The lates Node.js version as of writing is Node 16. You'll want to upgrade the frontend to use the latest Node.js version.

Some notes:
- The version of Node.js is specified here:  https://github.com/data-science-ucsb/gauchocourses/blob/main/frontend/pom.xml#L33
- I removed two packages when trying to resurrect this project. You may want to ad these packages back: https://github.com/data-science-ucsb/gauchocourses/pull/10/commits/d40c56d633c1f5838a99c79b5600e11bb537d373

Tasks:
- [x] Update Node.js to a supported version
- [x] Update the packages in package.json to their supported versions 
- [x] Ensure the application still builds and runs successfully

**Comment by WinbertZhang** [comment]
#13 Updated node and npm dependencies to Node 16

**Comment by JasonFreeberg** [comment]
Hey @WinbertZhang I made a mistake in my original issue, it looks like Node 18 is the current LTS version. Let's upgrade to 18.

The Node version for the **production** build of the app is specified here: https://github.com/data-science-ucsb/gauchocourses/blob/main/frontend/pom.xml#L33. So that's ultimately the final string that we need to update.

When you run "npm install" you'll notice that the logs will say _"warning: this package is no longer supported, upgrade to the latest version."_. So those are the warnings we want to address when I said "Update the packages in package.json to their supported versions"
