### ISSUE TITLE
Update the backend to Java 17, update Maven dependencies

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#12]
The project was originally implemented ~3 years ago with Java 8. Java 8 is going to EOL soon, so we'll need to update this to Java 17. 

Everyone on the team can download Java 17 here: https://learn.microsoft.com/en-us/java/openjdk/download

Tasks: 
- [x] Update maven poms to reference Java 17
- [x] Update the Dockerfile to use Java 17
- [x] Update Maven dependencies, their current versions may not work with 17
- [x] Ensure the application still builds and runs successfully

**Comment by WinbertZhang** [comment]
Updates in development branch 12. Builds and runs properly but still need to check run with the updated frontend once #16 
is fixed
