### ISSUE TITLE
Copy over Wiki articles to this repo

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#2]
The wiki for the code is here: https://github.com/crunch-time/crunchtime/wiki. It contains info about contributing, how the repo is structured, setting up local dev environments, etc.

Let's copy those articles over to the Wiki for this repo: https://github.com/data-science-ucsb/gauchocourses/wiki

**Comment by hallbrad** [comment]
+1

How can I or others get access to add/edit wikis?

**Comment by JasonFreeberg** [comment]
@WinbertZhang / @kshitij0407 Could you add @hallbrad as a contributor on the project? He's my friend and roommate from college and helped me implement app. He's gonna help answer questions as the devs get ramped up

**Comment by JasonFreeberg** [comment]
@hallbrad looks like I'm an admin so I just added you with write access, let me know if that doesn't work for the wiki

**Comment by hallbrad** [comment]
I was able to transfer them over. I'm editing the one for dev env setup. I'll mark this closed
