### ISSUE TITLE
Create Google OAuth App

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#3]
**Background:** The app is designed to use Google OAuth for authentication. This is the "sign in with Google" flow that you see all over the internet. "OAuth" is "Open Authentication Protocol" and it's an open standard, not anything Google-specific. When you see "Sign in with Facebook/Apple/etc" across the internet, those are OAuth flows as well, just using Facebook/Apple as the provider. 

When you create an OAuth app with Google, you will get two strings: a "client ID" and a "client secret". These strings are used by the GauchoCourses app here: https://github.com/crunch-time/crunchtime/blob/main/backend/src/main/resources/application-prod.properties#L30-L33

**Tasks**: 

A word of warning... it's probably best to do this using the club's Google account so the credentials can be passed down to future officers/members. If you use your personal account, then you'd have to give your password to the next cohort of students that work on this app!

- [x] Using club Google account, follow these instructions: https://developers.google.com/identity/sign-in/web/sign-in

You only need to do the numbered steps:
![image](https://user-images.githubusercontent.com/18747768/200043634-129c783d-965c-4fa9-b664-651419a988c3.png)

**Comment by JasonFreeberg** [comment]
@WinbertZhang I just remembered we'll need a duplicate app that the students can use for local development. 

![Image](https://user-images.githubusercontent.com/18747768/200079385-57abacba-07e3-4725-9c9f-cbeaaacc27a0.png)

**Comment by WinbertZhang** [comment]
![Image](https://user-images.githubusercontent.com/17103790/200203701-d63ef89f-0f68-49e6-8857-7caff65d8c85.png)

@JasonFreeberg I created the two OAuth 2.0 Client IDs under the datascienceucsb google account.

**Comment by JasonFreeberg** [comment]
@WinbertZhang Great! Closing this as done
