### ISSUE TITLE
Move Export to PDF Button Placement

### ISSUE THREAD

**Issue by WinbertZhang** [data-science-ucsb/gauchocourses#66]
- [x] Remove Export to PDF button from the schedule views and add only to the user's favorited schedules
- [x] Move the placement to the top right of the schedule box and **inside**

**Comment by Ramon-W** [comment]
Here's an example mockup. You can pick an icon from fontawesome since we are already using their library.
<img width="1055" alt="Screen Shot 2023-03-01 at 9 25 28 PM" src="https://user-images.githubusercontent.com/77691280/222338752-9a45ce3b-d694-442c-ad83-61796f7e70aa.png">
