### ISSUE TITLE
Create an account with UCSB Developer Portal & get an API key

### ISSUE THREAD

**Issue by JasonFreeberg** [data-science-ucsb/gauchocourses#9]
We'll need to create an account with the UCSB Developer Portal: https://developer.ucsb.edu/ and get an API Key to power the GauchoCourses app. The account should probably be made with the UCSB DS email so it can be transitioned easily in the future. 

Some terminology, similar to the OAuth task, you'll create an "App" with the developer portal which will give you access keys. Our app will need read access on these three APIs:

- Students - Student Record Code Lookups
- Academics - Academic Quarter Calendar
- Academics - Curriculums

IIRC you'll fill out a form and then someone from UCSB will email you to understand the purpose of your app and why you need access to their API's. Just describe the project's goals and explain that the app was approved 3 years ago, and we're just in the process of restarting it under the club's supervision. Feel free to CC me in that thread.

**Comment by JasonFreeberg** [comment]
Correction: we'll need **two** Apps. One for GauchoCourses running in production on Azure, and a second app for the devs to use during local development.

**Comment by WinbertZhang** [comment]
@JasonFreeberg I was able to create an account using my personal ucsb email but it looks like the registration page does not allow us to use gmail accounts, so we currently aren't able to make an account with the DS club email. Do we want to continue the app registration through my account or should we contact them about using the club email?

**Comment by JasonFreeberg** [comment]
Yeah go ahead and email them, I have my old API key we can use in the
meantime.

Best,
Jason
